### PR TITLE
First pass at notes on metrics-server.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by Mr0grog** [comment]
Is still relevant, given the work in #20? If so, let’s fix the conflict and just merge this in so these docs have some more visibility.

**Comment by danielballan** [comment]
Yes, still relevant. #20 builds on / relies on this. Rebased -- should be good to merge.

**Comment by danielballan** [comment]
I'm taking @Mr0grog's comment above as encouragement to self-merge this docs PR.

**Comment by Mr0grog** [comment]
Thanks!

**Pull request merged**
